platform :ios, '13.0'
#use_frameworks! #!! Do not enable, causes an error about "target has transitive dependencies that include static binaries.... "

def pods_for_all_targets
    pod 'VialerSIPLib', :path => '../'
end

target 'VialerSIPLib_Example' do
    pods_for_all_targets
    pod 'SwiftDate'
    pod 'SnackBar.swift'
    pod 'GoogleUtilities', :modular_headers => true
    pod 'FirebaseCore', :modular_headers => true
    pod 'FirebaseCoreInternal', :modular_headers => true
    pod 'FirebaseCrashlytics', :modular_headers => true
    pod 'Firebase/AnalyticsWithoutAdIdSupport', :modular_headers => true
end

target 'VialerSIPLib_Tests' do
    pods_for_all_targets
    pod 'OCMock'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PJ_AUTOCONF=1'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
